// screens/dashboard/CHAPTER/chapter3Data.js
const chapter3Image = require('../../../assets/chapter_covers/chapter 3.jpg');

export const chapter3Data = {
  number: 3,
  title: 'INSTALL APPLICATION SOFTWARE',
  description: 'Master the installation and configuration of essential software applications.',
  image: chapter3Image,
  sections: [
    {
      title: 'Software Installation Fundamentals',
      content: [
        'Application software installation must be based on software installation guides, end-user requirements, and software license agreements.',
        '',
        '[UPLOAD: image] Software Installation Overview',
        '',
        'Key Principles:',
        '• Follow software installation guides and documentation',
        '• Consider end-user requirements and needs',
        '• Respect software license agreements and terms',
        '• Install from trusted and official sources',
        '• Verify system compatibility before installation',
        '',
        'Software Sources and Licensing:',
        '',
        'Trusted Sources:',
        '• Official vendor websites - Most reliable source',
        '• Microsoft Store - For Windows applications',
        '• Organization-approved repositories - For enterprise environments',
        '• Original installation media - CDs, DVDs, or official downloads',
        '',
        '[UPLOAD: image] Trusted Software Sources',
        '',
        'Licensing Basics:',
        'Understanding software licenses is crucial:',
        '',
        'Types of Licenses:',
        '• Commercial/Proprietary - Requires purchase, restrictions on use',
        '• Freeware - Free to use but may have restrictions',
        '• Shareware - Trial version, may require payment for full features',
        '• Open Source - Free to use, modify, and distribute',
        '• Educational - Discounted or free for educational use',
        '',
        '[UPLOAD: image] License Types Comparison',
        '',
        'License Terms:',
        '• EULAs (End User License Agreements) - Read and understand terms',
        '• Per-device vs per-user licensing - Know what you\'re purchasing',
        '• Subscription vs perpetual licenses - Ongoing cost vs one-time',
        '• Number of installations allowed',
        '• Commercial use restrictions',
        '',
        '[UPLOAD: pdf] Understanding Software Licenses',
        '',
        'End-User Requirements:',
        'Before installing software, consider:',
        '• What tasks does the user need to perform?',
        '• What are the system requirements?',
        '• Is the software compatible with existing applications?',
        '• What are the user\'s skill levels?',
        '• Are there specific features needed?',
        '',
        '[UPLOAD: image] Requirements Analysis',
      ],
    },
    {
      title: 'Installing WinRAR',
      content: [
        'WinRAR is a powerful archive manager that can create and extract compressed files in various formats including RAR, ZIP, 7Z, and more.',
        '',
        '[UPLOAD: image] WinRAR Interface',
        '',
        'Downloading WinRAR:',
        '',
        '1. Visit the official WinRAR website (rarlab.com)',
        '',
        '2. Navigate to the download section',
        '',
        '3. Select the appropriate version:',
        '• Windows x64 (64-bit) for modern systems',
        '• Windows x86 (32-bit) for older systems',
        '',
        '[UPLOAD: image] WinRAR Download Page',
        '',
        '4. Download the installer file',
        '',
        '5. Save to a known location (e.g., Downloads folder)',
        '',
        '[UPLOAD: image] Download Location',
        '',
        'Installation Steps:',
        '',
        '1. Locate the downloaded installer file',
        '',
        '2. Right-click the installer and select "Run as administrator" (recommended)',
        '',
        '[UPLOAD: image] Run as Administrator',
        '',
        '3. If User Account Control (UAC) prompts, click "Yes"',
        '',
        '4. Installation wizard will start',
        '',
        '[UPLOAD: image] WinRAR Installation Wizard',
        '',
        '5. Choose installation location:',
        '• Default: C:\\Program Files\\WinRAR',
        '• Or click "Browse" to choose custom location',
        '',
        '[UPLOAD: image] Installation Location',
        '',
        '6. Configure installation options:',
        '• Associate WinRAR with: Select file types (RAR, ZIP, etc.)',
        '• Interface: Choose shell integration options',
        '• Select "Add WinRAR to desktop" if desired',
        '• Select "Add WinRAR to Start Menu" if desired',
        '',
        '[UPLOAD: image] Installation Options',
        '',
        '7. Click "Install" to begin installation',
        '',
        '8. Wait for installation to complete (usually takes less than a minute)',
        '',
        '[UPLOAD: image] Installation Progress',
        '',
        '9. Installation complete dialog will appear',
        '',
        '10. Click "OK" to finish',
        '',
        '[UPLOAD: image] Installation Complete',
        '',
        'Verification:',
        '',
        '1. Check Start Menu for WinRAR shortcut',
        '',
        '2. Right-click a file to see WinRAR options in context menu',
        '',
        '[UPLOAD: image] WinRAR Context Menu',
        '',
        '3. Launch WinRAR to verify it opens correctly',
        '',
        '4. Test by creating a compressed archive:',
        '• Right-click a file or folder',
        '• Select "Add to archive..."',
        '• Choose compression settings',
        '• Click "OK"',
        '',
        '[UPLOAD: image] Creating Archive',
        '',
        'Basic Usage:',
        '',
        'Creating Archives:',
        '• Right-click files/folders → "Add to archive..."',
        '• Or open WinRAR and drag files into it',
        '• Choose format (RAR, ZIP), compression level, and options',
        '',
        '[UPLOAD: image] Archive Creation Options',
        '',
        'Extracting Archives:',
        '• Right-click archive → "Extract files..." or "Extract here"',
        '• Or open archive in WinRAR and click "Extract To"',
        '',
        '[UPLOAD: image] Extracting Archives',
        '',
        'Key Features:',
        '• High compression ratio',
        '• Support for multiple archive formats',
        '• Password protection',
        '• Split archives for large files',
        '• Repair damaged archives',
        '',
        '[UPLOAD: video] WinRAR Installation and Basic Usage',
        '',
        '[UPLOAD: pdf] WinRAR User Manual',
      ],
    },
    {
      title: 'Installing Network Device Driver',
      content: [
        'Network device drivers are essential for network connectivity. This section covers installing network adapter drivers on Windows Server 2008 R2.',
        '',
        '[UPLOAD: image] Network Adapter',
        '',
        'Identifying Network Adapter:',
        '',
        '1. Open Device Manager:',
        '• Right-click "Computer" → "Manage" → "Device Manager"',
        '• Or press Windows + X → Device Manager',
        '',
        '[UPLOAD: image] Accessing Device Manager',
        '',
        '2. Look under "Network adapters" section',
        '',
        '3. If driver is missing, you may see:',
        '• "Ethernet Controller" under "Other devices"',
        '• Yellow exclamation mark (!)',
        '• "Unknown device"',
        '',
        '[UPLOAD: image] Missing Network Driver',
        '',
        '4. Note the device details:',
        '• Right-click the device → "Properties"',
        '• Go to "Details" tab',
        '• Select "Hardware Ids" from dropdown',
        '• Note the Vendor ID and Device ID (e.g., VEN_10EC&DEV_8168)',
        '',
        '[UPLOAD: image] Device Hardware IDs',
        '',
        'Downloading Network Driver:',
        '',
        'Method 1: From Motherboard Manufacturer',
        '1. Identify motherboard model (check documentation or use system information)',
        '',
        '2. Visit motherboard manufacturer website',
        '',
        '3. Navigate to support/downloads section',
        '',
        '4. Enter motherboard model',
        '',
        '5. Select operating system: Windows Server 2008 R2 x64',
        '',
        '6. Download LAN/Ethernet driver',
        '',
        '[UPLOAD: image] Motherboard Driver Download',
        '',
        'Method 2: From Network Adapter Manufacturer',
        '1. Identify network adapter chipset (from Hardware IDs)',
        '',
        '2. Common manufacturers:',
        '• Realtek (most common)',
        '• Intel',
        '• Broadcom',
        '• Qualcomm/Atheros',
        '',
        '3. Visit manufacturer website',
        '',
        '4. Download appropriate driver for Windows Server 2008 R2 x64',
        '',
        '[UPLOAD: image] Network Adapter Manufacturer Sites',
        '',
        'Method 3: Using Driver Update Tools',
        'Note: Use with caution, prefer official sources',
        '',
        '1. Download driver update utility',
        '',
        '2. Scan for missing drivers',
        '',
        '3. Download and install network driver',
        '',
        'Installing Network Driver:',
        '',
        'Method 1: Using Setup Executable',
        '1. Transfer driver files to the server (via USB if no network)',
        '',
        '2. Locate the driver installer (usually setup.exe)',
        '',
        '3. Right-click and select "Run as administrator"',
        '',
        '[UPLOAD: image] Running Driver Setup',
        '',
        '4. Follow installation wizard:',
        '• Accept license agreement',
        '• Choose installation location',
        '• Click "Install"',
        '',
        '[UPLOAD: image] Driver Installation Wizard',
        '',
        '5. Wait for installation to complete',
        '',
        '6. Restart if prompted',
        '',
        '[UPLOAD: image] Installation Complete',
        '',
        'Method 2: Manual Installation via Device Manager',
        '1. Open Device Manager',
        '',
        '2. Right-click the network device with issue',
        '',
        '3. Select "Update Driver Software"',
        '',
        '[UPLOAD: image] Update Driver Option',
        '',
        '4. Choose "Browse my computer for driver software"',
        '',
        '5. Click "Browse" and navigate to driver folder',
        '',
        '[UPLOAD: image] Browse for Driver',
        '',
        '6. Select the folder containing driver files',
        '',
        '7. Check "Include subfolders"',
        '',
        '8. Click "Next"',
        '',
        '9. Windows will search for and install the driver',
        '',
        '[UPLOAD: image] Driver Installation Progress',
        '',
        '10. Click "Close" when complete',
        '',
        'Verification:',
        '',
        '1. Check Device Manager:',
        '• Network adapter should appear under "Network adapters"',
        '• No yellow exclamation mark',
        '• Device shows as working properly',
        '',
        '[UPLOAD: image] Network Adapter Working',
        '',
        '2. Check Network Connections:',
        '• Open "Network and Sharing Center"',
        '• Click "Change adapter settings"',
        '• You should see your network adapter listed',
        '',
        '[UPLOAD: image] Network Connections',
        '',
        '3. Test Network Connectivity:',
        '• Connect network cable',
        '• Check for link lights on network adapter',
        '• Configure IP address (if needed)',
        '• Test ping to gateway or other devices',
        '',
        '[UPLOAD: image] Network Connectivity Test',
        '',
        'Troubleshooting:',
        '',
        'Issue: Driver installation fails',
        'Solutions:',
        '• Ensure you have administrator rights',
        '• Try compatibility mode (right-click installer → Properties → Compatibility)',
        '• Disable driver signature enforcement (advanced, not recommended)',
        '• Try different driver version',
        '',
        '[UPLOAD: image] Driver Installation Troubleshooting',
        '',
        'Issue: Network adapter not detected',
        'Solutions:',
        '• Check if adapter is enabled in BIOS',
        '• Reseat network adapter if it\'s a card',
        '• Check for hardware issues',
        '',
        'Issue: Limited or no connectivity',
        'Solutions:',
        '• Verify network cable connection',
        '• Check IP configuration',
        '• Verify network settings',
        '• Check firewall settings',
        '',
        '[UPLOAD: video] Complete Network Driver Installation',
        '',
        '[UPLOAD: pdf] Network Driver Installation Guide',
      ],
    },
    {
      title: 'Installing Kingsoft Office',
      content: [
        'Kingsoft Office (now WPS Office) is a free office suite that provides word processing, spreadsheet, and presentation applications compatible with Microsoft Office formats.',
        '',
        '[UPLOAD: image] Kingsoft Office Interface',
        '',
        'About Kingsoft Office:',
        'Kingsoft Office includes:',
        '• Writer - Word processing (similar to Microsoft Word)',
        '• Spreadsheets - Spreadsheet application (similar to Microsoft Excel)',
        '• Presentation - Presentation software (similar to Microsoft PowerPoint)',
        '',
        'Key Features:',
        '• Free to use',
        '• Compatible with Microsoft Office file formats (.docx, .xlsx, .pptx)',
        '• Lightweight and fast',
        '• Available in multiple languages',
        '',
        '[UPLOAD: image] Kingsoft Office Components',
        '',
        'Downloading Kingsoft Office:',
        '',
        '1. Visit the official Kingsoft/WPS Office website',
        '',
        'Note: Kingsoft Office has been rebranded as WPS Office, but installation process is similar',
        '',
        '2. Navigate to the download section',
        '',
        '3. Select version for Windows Server 2008 R2',
        '',
        '4. Choose between:',
        '• Free version',
        '• Professional version (if available)',
        '',
        '[UPLOAD: image] Kingsoft Office Download',
        '',
        '5. Download the installer',
        '',
        '6. Save to a known location',
        '',
        '[UPLOAD: image] Download Location',
        '',
        'Installation Steps:',
        '',
        '1. Locate the downloaded installer file',
        '',
        '2. Right-click and select "Run as administrator"',
        '',
        '[UPLOAD: image] Run Installer as Admin',
        '',
        '3. If UAC prompts, click "Yes"',
        '',
        '4. Installation wizard will start',
        '',
        '[UPLOAD: image] Installation Wizard Start',
        '',
        '5. Select installation language',
        '',
        '6. Read and accept the license agreement',
        '',
        '[UPLOAD: image] License Agreement',
        '',
        '7. Choose installation type:',
        '• Typical - Installs all components (recommended)',
        '• Custom - Allows selection of components',
        '• Complete - Installs all features including additional tools',
        '',
        '[UPLOAD: image] Installation Type',
        '',
        '8. If Custom installation selected:',
        '• Choose components to install:',
        '  - Writer (Word Processing)',
        '  - Spreadsheets',
        '  - Presentation',
        '  - Additional tools and templates',
        '',
        '[UPLOAD: image] Custom Installation Options',
        '',
        '9. Select installation directory:',
        '• Default: C:\\Program Files\\Kingsoft\\WPS Office',
        '• Or click "Browse" to choose custom location',
        '',
        '[UPLOAD: image] Installation Directory',
        '',
        '10. Choose additional options:',
        '• Create desktop shortcuts',
        '• Add to Start Menu',
        '• Set as default for Office documents',
        '• Create Quick Launch icon',
        '',
        '[UPLOAD: image] Additional Options',
        '',
        '11. Click "Install" to begin installation',
        '',
        '12. Wait for installation to complete',
        '',
        'Installation may take several minutes depending on system performance',
        '',
        '[UPLOAD: image] Installation Progress',
        '',
        '13. Installation complete dialog will appear',
        '',
        '14. Choose options:',
        '• Launch Kingsoft Office now',
        '• View readme file',
        '',
        '15. Click "Finish"',
        '',
        '[UPLOAD: image] Installation Complete',
        '',
        'Initial Setup:',
        '',
        '1. Launch Kingsoft Office',
        '',
        '2. First-time setup wizard may appear',
        '',
        '3. Configure preferences:',
        '• User information',
        '• Default file locations',
        '• Language settings',
        '• Template preferences',
        '',
        '[UPLOAD: image] Initial Setup',
        '',
        '4. Complete the setup wizard',
        '',
        'Verification:',
        '',
        '1. Check Start Menu for Kingsoft Office shortcuts',
        '',
        '[UPLOAD: image] Start Menu Shortcuts',
        '',
        '2. Launch each component:',
        '• Writer - Create a test document',
        '• Spreadsheets - Create a test spreadsheet',
        '• Presentation - Create a test presentation',
        '',
        '[UPLOAD: image] Testing Components',
        '',
        '3. Test file compatibility:',
        '• Open a Microsoft Word document (.docx)',
        '• Open a Microsoft Excel file (.xlsx)',
        '• Open a Microsoft PowerPoint file (.pptx)',
        '',
        '[UPLOAD: image] File Compatibility Test',
        '',
        '4. Test saving files:',
        '• Save in native Kingsoft format',
        '• Save in Microsoft Office format',
        '• Verify files can be opened in Microsoft Office',
        '',
        '[UPLOAD: image] Saving Files',
        '',
        'Basic Usage:',
        '',
        'Writer (Word Processing):',
        '• Create, edit, and format documents',
        '• Supports .doc, .docx formats',
        '• Similar interface to Microsoft Word',
        '',
        '[UPLOAD: image] Writer Interface',
        '',
        'Spreadsheets:',
        '• Create and manage spreadsheets',
        '• Supports formulas and functions',
        '• Compatible with .xls, .xlsx formats',
        '',
        '[UPLOAD: image] Spreadsheets Interface',
        '',
        'Presentation:',
        '• Create presentations with slides',
        '• Supports animations and transitions',
        '• Compatible with .ppt, .pptx formats',
        '',
        '[UPLOAD: image] Presentation Interface',
        '',
        'Configuration:',
        '',
        '1. Open any Kingsoft Office application',
        '',
        '2. Go to "Options" or "Preferences"',
        '',
        '3. Configure:',
        '• Default file locations',
        '• Auto-save settings',
        '• Language and regional settings',
        '• Display preferences',
        '',
        '[UPLOAD: image] Configuration Options',
        '',
        'Troubleshooting:',
        '',
        'Issue: Installation fails',
        'Solutions:',
        '• Run as administrator',
        '• Check system requirements',
        '• Disable antivirus temporarily',
        '• Check available disk space',
        '',
        'Issue: Files won\'t open',
        'Solutions:',
        '• Verify file format compatibility',
        '• Check if file is corrupted',
        '• Try opening in Microsoft Office first',
        '',
        'Issue: Application crashes',
        'Solutions:',
        '• Update to latest version',
        '• Reinstall the application',
        '• Check system resources (RAM, disk space)',
        '',
        '[UPLOAD: video] Complete Kingsoft Office Installation',
        '',
        '[UPLOAD: pdf] Kingsoft Office User Guide',
      ],
    },
    {
      title: 'Software Installation Best Practices',
      content: [
        'Following best practices ensures successful software installations and system stability.',
        '',
        '[UPLOAD: image] Best Practices Overview',
        '',
        'Pre-Installation:',
        '',
        '1. Read Documentation:',
        '• Review installation guides',
        '• Check system requirements',
        '• Understand license terms',
        '',
        '[UPLOAD: image] Reading Documentation',
        '',
        '2. Backup System:',
        '• Create system restore point',
        '• Backup important data',
        '• Document current system configuration',
        '',
        '[UPLOAD: image] Creating Restore Point',
        '',
        '3. Check Compatibility:',
        '• Verify OS compatibility',
        '• Check hardware requirements',
        '• Ensure sufficient disk space',
        '• Verify RAM requirements',
        '',
        '[UPLOAD: image] Compatibility Check',
        '',
        '4. Close Applications:',
        '• Close all running applications',
        '• Save all work',
        '• Close antivirus if needed (temporarily)',
        '',
        'During Installation:',
        '',
        '1. Run as Administrator:',
        '• Right-click installer → "Run as administrator"',
        '• Ensures proper permissions',
        '',
        '[UPLOAD: image] Run as Administrator',
        '',
        '2. Follow Installation Wizard:',
        '• Read each step carefully',
        '• Don\'t rush through options',
        '• Choose appropriate settings',
        '',
        '3. Custom Installation (when available):',
        '• Select only needed components',
        '• Choose appropriate installation location',
        '• Configure options properly',
        '',
        '[UPLOAD: image] Custom Installation',
        '',
        '4. Monitor Installation:',
        '• Watch for error messages',
        '• Don\'t interrupt the process',
        '• Note any warnings',
        '',
        'Post-Installation:',
        '',
        '1. Verify Installation:',
        '• Check Start Menu for shortcuts',
        '• Launch the application',
        '• Test basic functionality',
        '',
        '[UPLOAD: image] Verification Steps',
        '',
        '2. Update Software:',
        '• Check for updates',
        '• Install patches if available',
        '• Configure auto-updates if desired',
        '',
        '3. Configure Settings:',
        '• Set user preferences',
        '• Configure default file locations',
        '• Set up file associations',
        '',
        '[UPLOAD: image] Configuration',
        '',
        '4. Create Shortcuts:',
        '• Desktop shortcuts if needed',
        '• Taskbar pins if desired',
        '• Start Menu organization',
        '',
        '5. Test Functionality:',
        '• Create test files',
        '• Test file saving/opening',
        '• Verify integration with other software',
        '',
        '[UPLOAD: image] Testing Functionality',
        '',
        '6. Document Installation:',
        '• Note installation date',
        '• Record product keys/licenses',
        '• Save installation files',
        '• Document configuration',
        '',
        '[UPLOAD: image] Documentation',
        '',
        'Maintenance:',
        '',
        '1. Regular Updates:',
        '• Check for software updates regularly',
        '• Install security patches promptly',
        '• Keep software current',
        '',
        '2. Uninstallation:',
        '• Use proper uninstall methods',
        '• Use "Programs and Features" in Control Panel',
        '• Or use software\'s own uninstaller',
        '• Clean up residual files if needed',
        '',
        '[UPLOAD: image] Proper Uninstallation',
        '',
        '3. Repair Installation:',
        '• Use "Repair" option if software malfunctions',
        '• Available in "Programs and Features"',
        '• Often fixes issues without full reinstall',
        '',
        '[UPLOAD: image] Repair Installation',
        '',
        'Common Mistakes to Avoid:',
        '',
        '• Installing from untrusted sources',
        '• Skipping license agreements without reading',
        '• Installing unnecessary components',
        '• Interrupting installation process',
        '• Not creating restore points',
        '• Ignoring system requirements',
        '• Installing incompatible software',
        '',
        '[UPLOAD: pdf] Complete Installation Best Practices Guide',
        '',
        '[UPLOAD: video] Software Installation Best Practices',
      ],
    },
  ],
};
export default chapter3Data;