// screens/dashboard/CHAPTER/chapter4Data.js
const chapter4Image = require('../../../assets/chapter_covers/chapter 4.jpg');

export const chapter4Data = {
  number: 4,
  title: 'PC TROUBLESHOOTING TECHNIQUES',
  description: 'Develop systematic approaches to diagnose and resolve common problems.',
  image: chapter4Image,
  sections: [
    {
      title: 'Troubleshooting Methodology',
      content: [
        'A systematic approach to troubleshooting ensures efficient problem resolution and prevents further issues.',
        '',
        '[UPLOAD: image] Troubleshooting Process Flow',
        '',
        'Six-Step Troubleshooting Process:',
        '',
        'Step 1: Identify the Problem',
        'Gather information about the issue:',
        '• What are the exact symptoms?',
        '• When did the problem start?',
        '• What was happening when it occurred?',
        '• Has anything changed recently (hardware, software, settings)?',
        '• Does the problem occur consistently or intermittently?',
        '• What error messages appear (if any)?',
        '',
        '[UPLOAD: image] Problem Identification',
        '',
        'Step 2: Establish a Theory of Probable Cause',
        'Based on symptoms, develop possible causes:',
        '• Start with the most likely cause',
        '• Consider common issues first',
        '• Think about recent changes',
        '• Review similar past problems',
        '',
        '[UPLOAD: image] Theory Development',
        '',
        'Step 3: Test the Theory to Determine Cause',
        'Verify your theory through testing:',
        '• Use diagnostic tools',
        '• Test components individually',
        '• Check system logs',
        '• Verify configurations',
        '',
        'If theory is confirmed, proceed to step 4',
        'If theory is not confirmed, establish new theory and test again',
        '',
        '[UPLOAD: image] Testing Theory',
        '',
        'Step 4: Establish a Plan of Action and Implement the Fix',
        'Develop and execute solution:',
        '• Create step-by-step plan',
        '• Consider impact of changes',
        '• Have backup plan if fix fails',
        '• Implement fix carefully',
        '• Document each step',
        '',
        '[UPLOAD: image] Implementation Plan',
        '',
        'Step 5: Verify Full System Functionality',
        'Ensure problem is resolved:',
        '• Test the specific issue',
        '• Verify related functionality',
        '• Check for new issues',
        '• Confirm user satisfaction',
        '',
        '[UPLOAD: image] Verification Process',
        '',
        'Step 6: Document Findings, Actions, and Outcomes',
        'Record everything for future reference:',
        '• Problem description',
        '• Steps taken',
        '• Solution applied',
        '• Results',
        '• Time taken',
        '• Parts replaced (if any)',
        '',
        '[UPLOAD: image] Documentation',
        '',
        'General Troubleshooting Tips:',
        '',
        '• Start simple, work toward complex',
        '• Check physical connections first',
        '• Verify power before assuming hardware failure',
        '• Use known-good components for testing',
        '• Keep spare parts for testing',
        '• Don\'t assume - verify',
        '• Take notes throughout the process',
        '',
        '[UPLOAD: pdf] Complete Troubleshooting Methodology Guide',
        '',
        '[UPLOAD: video] Troubleshooting Methodology Overview',
      ],
    },
    {
      title: 'Troubleshooting Tips for New Monitor',
      content: [
        'When installing or troubleshooting a new monitor, follow these systematic steps.',
        '',
        '[UPLOAD: image] Monitor Setup',
        '',
        'Initial Setup Issues:',
        '',
        '1. No Display/Black Screen:',
        '',
        'Check Physical Connections:',
        '• Verify power cable is connected and power button is on',
        '• Check video cable connection (VGA, DVI, HDMI, DisplayPort)',
        '• Ensure cable is securely connected at both ends',
        '• Try a different video cable if available',
        '',
        '[UPLOAD: image] Monitor Connections',
        '',
        'Check Video Source:',
        '• Verify correct input source is selected on monitor',
        '• Try different input ports (HDMI 1, HDMI 2, etc.)',
        '• Check if computer is sending signal (check other monitor)',
        '',
        '[UPLOAD: image] Input Source Selection',
        '',
        'Check Graphics:',
        '• Verify graphics card/driver is working',
        '• Try onboard graphics if available',
        '• Check if monitor is detected in Display Settings',
        '',
        '2. Display Issues:',
        '',
        'Resolution Problems:',
        '• Right-click desktop → Display Settings',
        '• Select recommended resolution',
        '• Adjust scaling if text is too small/large',
        '',
        '[UPLOAD: image] Display Settings',
        '',
        'Color/Image Quality:',
        '• Adjust brightness and contrast',
        '• Check color calibration',
        '• Update graphics drivers',
        '• Try different color profile',
        '',
        '[UPLOAD: image] Color Calibration',
        '',
        'Flickering Screen:',
        '• Check refresh rate settings',
        '• Try different refresh rate (60Hz, 75Hz, etc.)',
        '• Check cable quality',
        '• Update graphics drivers',
        '',
        '[UPLOAD: image] Refresh Rate Settings',
        '',
        '3. Monitor Not Detected:',
        '',
        'Windows Detection:',
        '• Press Windows + P to check display mode',
        '• Try "Detect" in Display Settings',
        '• Check Device Manager for monitor',
        '• Update graphics drivers',
        '',
        '[UPLOAD: image] Display Detection',
        '',
        '4. Physical Issues:',
        '',
        'Dead Pixels:',
        '• Check for stuck or dead pixels',
        '• Use pixel testing software',
        '• Contact manufacturer if under warranty',
        '',
        '[UPLOAD: image] Pixel Test',
        '',
        'Backlight Issues:',
        '• Check if backlight is working',
        '• Adjust brightness settings',
        '• May require professional repair',
        '',
        '5. Compatibility Issues:',
        '',
        'Resolution Support:',
        '• Verify monitor resolution is supported by graphics card',
        '• Check maximum resolution of graphics adapter',
        '',
        'Refresh Rate:',
        '• Ensure graphics card supports monitor\'s refresh rate',
        '• Check cable bandwidth limitations',
        '',
        '[UPLOAD: image] Compatibility Check',
        '',
        'Quick Diagnostic Steps:',
        '',
        '1. Test monitor on another computer',
        '2. Test another monitor on same computer',
        '3. Try different video cable',
        '4. Update graphics drivers',
        '5. Check BIOS settings for display',
        '',
        '[UPLOAD: video] Monitor Troubleshooting Guide',
        '',
        '[UPLOAD: pdf] Monitor Troubleshooting Checklist',
      ],
    },
    {
      title: 'Troubleshooting Tips for New Motherboard',
      content: [
        'Installing a new motherboard requires careful attention to detail. Follow these troubleshooting steps if issues arise.',
        '',
        '[UPLOAD: image] Motherboard Installation',
        '',
        'Pre-Installation:',
        '',
        '1. Verify Compatibility:',
        '• Check CPU socket compatibility',
        '• Verify RAM type (DDR3, DDR4, DDR5)',
        '• Ensure case form factor matches (ATX, mATX, ITX)',
        '• Check PSU connectors match',
        '',
        '[UPLOAD: image] Compatibility Verification',
        '',
        '2. Prepare Workspace:',
        '• Use anti-static mat',
        '• Have proper tools ready',
        '• Good lighting',
        '• Read motherboard manual',
        '',
        '[UPLOAD: image] Workspace Setup',
        '',
        'Installation Issues:',
        '',
        '1. System Won\'t Power On:',
        '',
        'Check Power Connections:',
        '• Verify 24-pin ATX connector is fully seated',
        '• Check 8-pin (or 4+4) CPU power connector',
        '• Ensure PSU switch is on',
        '• Check power button connection to motherboard',
        '',
        '[UPLOAD: image] Power Connections',
        '',
        'Check Front Panel Connections:',
        '• Verify power switch (PWR_SW) is connected correctly',
        '• Check polarity (usually doesn\'t matter for switches)',
        '• Refer to motherboard manual for pinout',
        '',
        '[UPLOAD: image] Front Panel Connections',
        '',
        '2. No POST (Power-On Self-Test):',
        '',
        'Check CPU Installation:',
        '• Verify CPU is correctly seated',
        '• Check for bent pins (if PGA socket)',
        '• Ensure CPU cooler is properly mounted',
        '• Check CPU power connector',
        '',
        '[UPLOAD: image] CPU Installation Check',
        '',
        'Check RAM:',
        '• Ensure RAM is fully seated',
        '• Try one stick at a time',
        '• Test RAM in different slots',
        '• Verify RAM compatibility',
        '',
        '[UPLOAD: image] RAM Troubleshooting',
        '',
        'Check for Shorts:',
        '• Ensure motherboard is not touching case',
        '• Check standoffs are in correct positions',
        '• Verify no extra standoffs causing shorts',
        '',
        '[UPLOAD: image] Standoff Check',
        '',
        '3. POST Beep Codes:',
        '',
        'Listen for beep patterns:',
        '• Continuous beeps: Power issue',
        '• One long, two short: Graphics issue',
        '• One long, three short: RAM issue',
        '• No beeps: Motherboard or PSU issue',
        '',
        'Refer to motherboard manual for specific beep codes',
        '',
        '[UPLOAD: image] Beep Code Reference',
        '',
        '4. BIOS/UEFI Issues:',
        '',
        'Cannot Access BIOS:',
        '• Try different keys (Del, F2, F10, F12, Esc)',
        '• Press key repeatedly during boot',
        '• Clear CMOS if needed',
        '',
        '[UPLOAD: image] BIOS Access',
        '',
        'CMOS Reset:',
        '• Power off and unplug computer',
        '• Remove CMOS battery for 5 minutes',
        '• Or use CMOS jumper (refer to manual)',
        '• Reinstall battery and power on',
        '',
        '[UPLOAD: image] CMOS Reset',
        '',
        '5. Component Recognition Issues:',
        '',
        'Hardware Not Detected:',
        '• Check Device Manager',
        '• Verify components are properly connected',
        '• Update BIOS/UEFI firmware',
        '• Install chipset drivers',
        '',
        '[UPLOAD: image] Device Recognition',
        '',
        '6. Boot Issues:',
        '',
        'Cannot Boot from Drive:',
        '• Check SATA cable connections',
        '• Verify boot order in BIOS',
        '• Check SATA mode (AHCI/IDE/RAID)',
        '• Ensure drive has operating system',
        '',
        '[UPLOAD: image] Boot Configuration',
        '',
        '7. USB Ports Not Working:',
        '',
        'Troubleshooting:',
        '• Check USB headers are connected',
        '• Try different USB ports',
        '• Update chipset drivers',
        '• Check BIOS USB settings',
        '',
        '[UPLOAD: image] USB Troubleshooting',
        '',
        '8. Audio Issues:',
        '',
        'No Sound:',
        '• Verify front panel audio header connection',
        '• Check rear audio ports',
        '• Install audio drivers',
        '• Check BIOS audio settings',
        '',
        '[UPLOAD: image] Audio Connections',
        '',
        'Best Practices:',
        '',
        '• Read motherboard manual thoroughly',
        '• Install standoffs correctly',
        '• Connect all power connectors',
        '• Install components in proper order',
        '• Update BIOS to latest version',
        '• Install chipset drivers first',
        '',
        '[UPLOAD: video] Motherboard Installation and Troubleshooting',
        '',
        '[UPLOAD: pdf] Motherboard Troubleshooting Guide',
      ],
    },
    {
      title: 'Troubleshooting Tips After Installing a New Hard Drive',
      content: [
        'After installing a new hard drive, you may encounter various issues. Follow these troubleshooting steps.',
        '',
        '[UPLOAD: image] Hard Drive Installation',
        '',
        'Initial Detection Issues:',
        '',
        '1. Drive Not Detected in BIOS:',
        '',
        'Check Physical Connections:',
        '• Verify SATA data cable is connected',
        '• Check SATA power cable is connected',
        '• Ensure cables are fully seated',
        '• Try different SATA ports',
        '• Try different SATA cables',
        '',
        '[UPLOAD: image] SATA Connections',
        '',
        'Check Power:',
        '• Verify PSU has available SATA power connector',
        '• Check if drive spins (listen for sound)',
        '• Try different power connector',
        '',
        '[UPLOAD: image] Power Connection',
        '',
        'BIOS Settings:',
        '• Enter BIOS/UEFI',
        '• Check SATA controller is enabled',
        '• Verify SATA mode (AHCI recommended)',
        '• Check if drive appears in storage devices',
        '',
        '[UPLOAD: image] BIOS SATA Settings',
        '',
        '2. Drive Not Detected in Windows:',
        '',
        'Disk Management:',
        '• Press Windows + X → Disk Management',
        '• Look for unallocated disk space',
        '• Drive may need initialization',
        '',
        '[UPLOAD: image] Disk Management',
        '',
        'Initialize Disk:',
        '• Right-click unallocated space',
        '• Select "Initialize Disk"',
        '• Choose MBR or GPT partition style',
        '• GPT for drives over 2TB or UEFI systems',
        '• MBR for older systems or drives under 2TB',
        '',
        '[UPLOAD: image] Initialize Disk',
        '',
        'Create Partition:',
        '• Right-click unallocated space',
        '• Select "New Simple Volume"',
        '• Follow wizard to create partition',
        '• Assign drive letter',
        '• Format with NTFS (for Windows)',
        '',
        '[UPLOAD: image] Create Partition',
        '',
        '3. Drive Shows Wrong Capacity:',
        '',
        'Possible Causes:',
        '• Drive not fully initialized',
        '• Partition not created',
        '• Using MBR on large drive (2TB+ limit)',
        '',
        'Solution:',
        '• Initialize as GPT for large drives',
        '• Create partition using all space',
        '',
        '[UPLOAD: image] Capacity Issues',
        '',
        '4. Drive Not Showing Full Capacity:',
        '',
        'Check:',
        '• Some space may be unallocated',
        '• Check Disk Management for all space',
        '• Create additional partition if needed',
        '',
        'Performance Issues:',
        '',
        '1. Slow Performance:',
        '',
        'Check Drive Health:',
        '• Use SMART monitoring tools',
        '• Check for errors',
        '• Run disk check',
        '',
        '[UPLOAD: image] Drive Health Check',
        '',
        'Optimize Drive:',
        '• For HDD: Defragment drive',
        '• For SSD: TRIM is automatic, but can optimize',
        '• Right-click drive → Properties → Tools → Optimize',
        '',
        '[UPLOAD: image] Drive Optimization',
        '',
        'Check SATA Mode:',
        '• Ensure AHCI mode is enabled in BIOS',
        '• Better performance than IDE mode',
        '',
        '2. Drive Making Noise:',
        '',
        'Normal Sounds:',
        '• HDDs make some noise during operation',
        '• Clicking during read/write is normal',
        '',
        'Concerning Sounds:',
        '• Loud clicking or grinding',
        '• Repeated clicking',
        '• May indicate mechanical failure',
        '• Backup data immediately',
        '',
        '[UPLOAD: image] Drive Noise Reference',
        '',
        'Installation as Boot Drive:',
        '',
        '1. Install Operating System:',
        '• Boot from installation media',
        '• Select new drive for installation',
        '• Follow OS installation process',
        '',
        '[UPLOAD: image] OS Installation',
        '',
        '2. Set Boot Order:',
        '• Enter BIOS/UEFI',
        '• Set new drive as first boot device',
        '• Save and exit',
        '',
        '[UPLOAD: image] Boot Order',
        '',
        '3. Clone Existing Drive:',
        'If migrating from old drive:',
        '• Use cloning software (Clonezilla, Macrium, etc.)',
        '• Clone entire drive including OS',
        '• Set new drive as boot device',
        '',
        '[UPLOAD: image] Drive Cloning',
        '',
        'Common Errors:',
        '',
        'Error: "Disk is write protected"',
        'Solution:',
        '• Check physical write-protect switch (if present)',
        '• Check disk properties',
        '• Use diskpart to remove protection',
        '',
        '[UPLOAD: image] Write Protection',
        '',
        'Error: "The parameter is incorrect"',
        'Solution:',
        '• Run disk check: chkdsk /f',
        '• Check for file system errors',
        '• May need to reformat',
        '',
        'Error: Drive appears but cannot access',
        'Solution:',
        '• Check drive letter assignment',
        '• Assign drive letter in Disk Management',
        '• Check permissions',
        '',
        '[UPLOAD: image] Drive Access Issues',
        '',
        'Best Practices:',
        '',
        '• Always backup data before operations',
        '• Use proper anti-static precautions',
        '• Handle drives carefully',
        '• Ensure adequate power supply',
        '• Use quality SATA cables',
        '• Keep drives cool and well-ventilated',
        '• Regularly check drive health',
        '',
        '[UPLOAD: video] Hard Drive Installation and Troubleshooting',
        '',
        '[UPLOAD: pdf] Hard Drive Troubleshooting Guide',
      ],
    },
    {
      title: 'Troubleshooting for Network Card',
      content: [
        'Network connectivity issues can stem from various causes. Follow these steps to troubleshoot network card problems.',
        '',
        '[UPLOAD: image] Network Card',
        '',
        '1. Network Card Not Detected:',
        '',
        'Check Device Manager:',
        '• Open Device Manager',
        '• Look under "Network adapters"',
        '• Check for yellow exclamation mark',
        '• May appear as "Unknown device" or "Ethernet Controller"',
        '',
        '[UPLOAD: image] Device Manager Network',
        '',
        'Install Driver:',
        '• Download driver from manufacturer',
        '• Install driver manually if needed',
        '• Use Windows Update to find driver',
        '',
        '[UPLOAD: image] Driver Installation',
        '',
        'Check Physical Installation:',
        '• If expansion card, ensure it\'s properly seated',
        '• Check PCI/PCIe slot',
        '• Verify card is enabled in BIOS',
        '',
        '[UPLOAD: image] Physical Installation',
        '',
        '2. No Network Connection:',
        '',
        'Check Physical Connection:',
        '• Verify network cable is connected',
        '• Check cable is not damaged',
        '• Verify cable is connected to correct port',
        '• Check link lights on network adapter',
        '• Try different network cable',
        '',
        '[UPLOAD: image] Physical Connection Check',
        '',
        'Check Network Settings:',
        '• Open Network and Sharing Center',
        '• Check adapter status',
        '• Verify adapter is enabled',
        '',
        '[UPLOAD: image] Network Settings',
        '',
        'Check IP Configuration:',
        '• Open Command Prompt as administrator',
        '• Run: ipconfig /all',
        '• Check if IP address is assigned',
        '• Verify gateway and DNS settings',
        '',
        '[UPLOAD: image] IP Configuration',
        '',
        '3. Limited or No Connectivity:',
        '',
        'Renew IP Address:',
        '• Open Command Prompt as administrator',
        '• Run: ipconfig /release',
        '• Then: ipconfig /renew',
        '',
        '[UPLOAD: image] IP Renewal',
        '',
        'Flush DNS:',
        '• Run: ipconfig /flushdns',
        '• Clears DNS cache',
        '',
        '[UPLOAD: image] DNS Flush',
        '',
        'Reset Network Stack:',
        '• Run: netsh winsock reset',
        '• Then: netsh int ip reset',
        '• Restart computer',
        '',
        '[UPLOAD: image] Network Reset',
        '',
        '4. Slow Network Speed:',
        '',
        'Check Connection Speed:',
        '• Verify adapter speed (10/100/1000 Mbps)',
        '• Check if running at full speed',
        '• May need to set speed manually',
        '',
        '[UPLOAD: image] Speed Settings',
        '',
        'Update Driver:',
        '• Install latest network driver',
        '• Check manufacturer website',
        '',
        'Check for Interference:',
        '• If wireless, check signal strength',
        '• Avoid interference sources',
        '• Try different channel',
        '',
        '[UPLOAD: image] Wireless Settings',
        '',
        '5. Network Card Disconnects Frequently:',
        '',
        'Check Power Management:',
        '• Open Device Manager',
        '• Right-click network adapter → Properties',
        '• Go to Power Management tab',
        '• Uncheck "Allow computer to turn off this device"',
        '',
        '[UPLOAD: image] Power Management',
        '',
        'Update Driver:',
        '• Outdated drivers can cause disconnections',
        '• Install latest driver version',
        '',
        'Check Cable:',
        '• Faulty cable can cause intermittent issues',
        '• Try different cable',
        '',
        '6. Cannot Access Internet:',
        '',
        'Ping Tests:',
        '• Ping loopback: ping 127.0.0.1',
        '• Ping gateway: ping [gateway IP]',
        '• Ping DNS: ping 8.8.8.8',
        '• Ping website: ping google.com',
        '',
        '[UPLOAD: image] Ping Tests',
        '',
        'Check Firewall:',
        '• Verify firewall is not blocking',
        '• Check Windows Firewall settings',
        '• Temporarily disable to test',
        '',
        '[UPLOAD: image] Firewall Settings',
        '',
        'Check Proxy Settings:',
        '• Verify proxy configuration',
        '• Disable if not needed',
        '',
        '[UPLOAD: image] Proxy Settings',
        '',
        '7. Driver Issues:',
        '',
        'Update Driver:',
        '• Use Device Manager to update',
        '• Or download from manufacturer',
        '',
        'Rollback Driver:',
        '• If update caused issues',
        '• Device Manager → Properties → Driver → Rollback',
        '',
        '[UPLOAD: image] Driver Rollback',
        '',
        'Uninstall and Reinstall:',
        '• Remove driver completely',
        '• Restart computer',
        '• Let Windows reinstall or install manually',
        '',
        '[UPLOAD: image] Driver Reinstall',
        '',
        '8. Advanced Troubleshooting:',
        '',
        'Check Event Viewer:',
        '• Open Event Viewer',
        '• Check System logs for network errors',
        '• Look for error codes',
        '',
        '[UPLOAD: image] Event Viewer',
        '',
        'Network Diagnostics:',
        '• Right-click network icon → Troubleshoot problems',
        '• Let Windows diagnose issues',
        '',
        '[UPLOAD: image] Network Diagnostics',
        '',
        'Test with Another Device:',
        '• Connect another device to same network',
        '• Verify if issue is with card or network',
        '',
        '[UPLOAD: video] Complete Network Card Troubleshooting',
        '',
        '[UPLOAD: pdf] Network Troubleshooting Guide',
      ],
    },
    {
      title: 'Troubleshooting for Sound Card',
      content: [
        'Audio issues can be frustrating. Follow these steps to troubleshoot sound card problems.',
        '',
        '[UPLOAD: image] Sound Card',
        '',
        '1. No Sound at All:',
        '',
        'Check Physical Connections:',
        '• Verify speakers/headphones are connected',
        '• Check connection to correct port (usually green)',
        '• Ensure speakers are powered on',
        '• Check volume on speakers',
        '• Try different speakers/headphones',
        '',
        '[UPLOAD: image] Audio Connections',
        '',
        'Check Windows Volume:',
        '• Click volume icon in system tray',
        '• Ensure volume is not muted',
        '• Check volume level',
        '',
        '[UPLOAD: image] Windows Volume',
        '',
        'Check Sound Settings:',
        '• Right-click volume icon → Open Sound settings',
        '• Verify correct output device is selected',
        '• Check device is not disabled',
        '',
        '[UPLOAD: image] Sound Settings',
        '',
        '2. Sound Card Not Detected:',
        '',
        'Check Device Manager:',
        '• Open Device Manager',
        '• Look under "Sound, video and game controllers"',
        '• Check for yellow exclamation mark',
        '• May appear as "High Definition Audio Device" or "Unknown device"',
        '',
        '[UPLOAD: image] Device Manager Audio',
        '',
        'Install Driver:',
        '• Download audio driver from motherboard manufacturer',
        '• Or from audio chipset manufacturer (Realtek, etc.)',
        '• Install driver and restart',
        '',
        '[UPLOAD: image] Audio Driver Installation',
        '',
        'Check BIOS:',
        '• Enter BIOS/UEFI',
        '• Verify onboard audio is enabled',
        '• May be listed as "HD Audio" or "Audio Controller"',
        '',
        '[UPLOAD: image] BIOS Audio Settings',
        '',
        '3. Sound is Distorted or Crackling:',
        '',
        'Update Driver:',
        '• Outdated drivers can cause distortion',
        '• Install latest audio driver',
        '',
        'Check Sample Rate:',
        '• Right-click volume icon → Sounds → Playback',
        '• Select device → Properties → Advanced',
        '• Try different sample rate and bit depth',
        '• Common: 44100 Hz, 16 bit or 48000 Hz, 16 bit',
        '',
        '[UPLOAD: image] Audio Format Settings',
        '',
        'Check for Interference:',
        '• Move speakers away from other electronics',
        '• Check cable quality',
        '• Try different audio cable',
        '',
        '4. Only One Speaker Working:',
        '',
        'Check Balance:',
        '• Right-click volume icon → Sounds → Playback',
        '• Select device → Properties → Levels',
        '• Check balance settings',
        '',
        '[UPLOAD: image] Balance Settings',
        '',
        'Check Cable:',
        '• Verify stereo cable is fully inserted',
        '• Try different cable',
        '• Check if mono/stereo switch on speakers',
        '',
        'Test Speakers:',
        '• Test speakers on another device',
        '• Verify speakers are working',
        '',
        '5. Microphone Not Working:',
        '',
        'Check Connection:',
        '• Verify microphone is connected to correct port (usually pink)',
        '• Check if microphone requires power',
        '',
        '[UPLOAD: image] Microphone Connection',
        '',
        'Check Microphone Settings:',
        '• Right-click volume icon → Sounds → Recording',
        '• Verify microphone is enabled and set as default',
        '• Check microphone levels',
        '',
        '[UPLOAD: image] Microphone Settings',
        '',
        'Enable Microphone:',
        '• Some systems require enabling in settings',
        '• Check privacy settings for microphone access',
        '',
        '[UPLOAD: image] Microphone Privacy',
        '',
        '6. Sound Works But Very Quiet:',
        '',
        'Check Volume Levels:',
        '• Increase Windows volume',
        '• Increase application volume',
        '• Check speaker volume control',
        '',
        'Check Audio Enhancements:',
        '• Right-click volume icon → Sounds → Playback',
        '• Select device → Properties → Enhancements',
        '• Try disabling enhancements',
        '',
        '[UPLOAD: image] Audio Enhancements',
        '',
        '7. Sound Delay/Latency:',
        '',
        'Check Buffer Settings:',
        '• Some audio software allows buffer adjustment',
        '• Lower buffer = less latency but may cause issues',
        '• Higher buffer = more stable but more latency',
        '',
        'Update Driver:',
        '• Newer drivers may have better latency',
        '',
        '8. Front Panel Audio Not Working:',
        '',
        'Check Front Panel Connection:',
        '• Verify HD Audio connector is connected to motherboard',
        '• Check connection matches motherboard manual',
        '• Ensure connector is fully seated',
        '',
        '[UPLOAD: image] Front Panel Audio Connection',
        '',
        'Check Software Settings:',
        '• Some audio drivers have front panel detection',
        '• Enable front panel in audio software',
        '',
        '[UPLOAD: image] Front Panel Settings',
        '',
        '9. Driver Issues:',
        '',
        'Update Driver:',
        '• Download latest from manufacturer',
        '• Use Device Manager to update',
        '',
        'Rollback Driver:',
        '• If update caused issues',
        '• Device Manager → Properties → Driver → Rollback',
        '',
        '[UPLOAD: image] Driver Management',
        '',
        'Uninstall and Reinstall:',
        '• Remove audio device in Device Manager',
        '• Restart computer',
        '• Let Windows reinstall or install manually',
        '',
        '10. Advanced Troubleshooting:',
        '',
        'Check Audio Service:',
        '• Press Windows + R → services.msc',
        '• Find "Windows Audio" service',
        '• Ensure it\'s running and set to Automatic',
        '',
        '[UPLOAD: image] Audio Service',
        '',
        'Test with Different Application:',
        '• Try different media player',
        '• Test with system sounds',
        '• Verify if issue is application-specific',
        '',
        'Check for Conflicting Software:',
        '• Some software can interfere with audio',
        '• Temporarily disable antivirus',
        '• Check for audio enhancement software conflicts',
        '',
        '[UPLOAD: video] Complete Sound Card Troubleshooting',
        '',
        '[UPLOAD: pdf] Audio Troubleshooting Guide',
      ],
    },
    {
      title: 'Computer Virus: Types and Installing Anti-virus Software',
      content: [
        'Understanding computer viruses and implementing proper protection is essential for system security.',
        '',
        '[UPLOAD: image] Computer Virus Overview',
        '',
        'Types of Computer Viruses:',
        '',
        '1. File Infector Viruses:',
        '• Attach to executable files (.exe, .com)',
        '• Spread when infected file is executed',
        '• Can corrupt or delete files',
        '',
        '[UPLOAD: image] File Infector',
        '',
        '2. Boot Sector Viruses:',
        '• Infect boot sector of hard drive',
        '• Load before operating system',
        '• Can prevent system from booting',
        '',
        '[UPLOAD: image] Boot Sector Virus',
        '',
        '3. Macro Viruses:',
        '• Embedded in documents (Word, Excel)',
        '• Execute when document is opened',
        '• Can spread via email attachments',
        '',
        '[UPLOAD: image] Macro Virus',
        '',
        '4. Worms:',
        '• Self-replicating malware',
        '• Spread over networks',
        '• Don\'t need host file',
        '• Can consume bandwidth and resources',
        '',
        '[UPLOAD: image] Computer Worm',
        '',
        '5. Trojan Horses:',
        '• Disguised as legitimate software',
        '• Appear harmless but contain malicious code',
        '• Don\'t replicate but can open backdoors',
        '',
        '[UPLOAD: image] Trojan Horse',
        '',
        '6. Spyware:',
        '• Collects information without permission',
        '• Tracks browsing habits',
        '• Can steal passwords and personal data',
        '',
        '[UPLOAD: image] Spyware',
        '',
        '7. Ransomware:',
        '• Encrypts files and demands payment',
        '• Prevents access to data',
        '• Very dangerous and difficult to remove',
        '',
        '[UPLOAD: image] Ransomware',
        '',
        '8. Adware:',
        '• Displays unwanted advertisements',
        '• Can slow down system',
        '• Often bundled with free software',
        '',
        '[UPLOAD: image] Adware',
        '',
        'Virus Symptoms:',
        '',
        'Common Signs of Infection:',
        '• Slow computer performance',
        '• Frequent crashes or freezes',
        '• Unexpected pop-up messages',
        '• Files missing or corrupted',
        '• Unusual hard drive activity',
        '• Programs won\'t start',
        '• Browser homepage changed',
        '• New toolbars or icons',
        '• Email sending without your knowledge',
        '• Antivirus disabled',
        '',
        '[UPLOAD: image] Virus Symptoms',
        '',
        'Installing Anti-virus Software:',
        '',
        'Choosing Anti-virus Software:',
        '',
        'Popular Options:',
        '• Windows Defender (built-in, free)',
        '• Avast (free and paid versions)',
        '• AVG (free and paid versions)',
        '• Kaspersky (paid)',
        '• Norton (paid)',
        '• McAfee (paid)',
        '• Bitdefender (free and paid)',
        '',
        '[UPLOAD: image] Antivirus Options',
        '',
        'Considerations:',
        '• System resource usage',
        '• Detection rates',
        '• Ease of use',
        '• Cost',
        '• Real-time protection',
        '• Update frequency',
        '',
        'Installing Windows Defender (Built-in):',
        '',
        'Windows Defender is included with Windows:',
        '',
        '1. Open Windows Security:',
        '• Press Windows + I → Update & Security → Windows Security',
        '• Or search "Windows Security" in Start Menu',
        '',
        '[UPLOAD: image] Windows Security',
        '',
        '2. Verify Protection:',
        '• Check "Virus & threat protection"',
        '• Ensure real-time protection is on',
        '• Verify definitions are up to date',
        '',
        '[UPLOAD: image] Windows Defender Settings',
        '',
        '3. Run Scan:',
        '• Click "Quick scan" or "Full scan"',
        '• Review results',
        '',
        '[UPLOAD: image] Windows Defender Scan',
        '',
        'Installing Third-Party Anti-virus:',
        '',
        'Example: Installing Avast Free Antivirus',
        '',
        '1. Download:',
        '• Visit official Avast website',
        '• Download free version',
        '• Save installer',
        '',
        '[UPLOAD: image] Avast Download',
        '',
        '2. Install:',
        '• Run installer',
        '• Follow installation wizard',
        '• Accept license agreement',
        '• Choose installation type',
        '',
        '[UPLOAD: image] Avast Installation',
        '',
        '3. Configure:',
        '• Set up initial scan',
        '• Configure real-time protection',
        '• Set update preferences',
        '',
        '[UPLOAD: image] Avast Configuration',
        '',
        '4. Update:',
        '• Ensure virus definitions are updated',
        '• Set automatic updates',
        '',
        '[UPLOAD: image] Antivirus Updates',
        '',
        'Best Practices:',
        '',
        '1. Keep Antivirus Updated:',
        '• Enable automatic updates',
        '• Check for updates regularly',
        '• New threats emerge daily',
        '',
        '[UPLOAD: image] Update Settings',
        '',
        '2. Regular Scans:',
        '• Schedule full system scans',
        '• Quick scans daily',
        '• Full scans weekly',
        '',
        '[UPLOAD: image] Scan Schedule',
        '',
        '3. Real-time Protection:',
        '• Keep real-time protection enabled',
        '• Scans files as they\'re accessed',
        '• Blocks threats immediately',
        '',
        '[UPLOAD: image] Real-time Protection',
        '',
        '4. Safe Browsing:',
        '• Don\'t click suspicious links',
        '• Don\'t download from untrusted sources',
        '• Be cautious with email attachments',
        '',
        '[UPLOAD: image] Safe Browsing',
        '',
        '5. Keep System Updated:',
        '• Install Windows updates',
        '• Update other software',
        '• Patches security vulnerabilities',
        '',
        '[UPLOAD: image] System Updates',
        '',
        '6. Backup Important Data:',
        '• Regular backups protect against ransomware',
        '• Use external drives or cloud storage',
        '• Test backup restoration',
        '',
        '[UPLOAD: image] Data Backup',
        '',
        '7. Use Firewall:',
        '• Enable Windows Firewall',
        '• Or use third-party firewall',
        '• Blocks unauthorized access',
        '',
        '[UPLOAD: image] Firewall Settings',
        '',
        'Removing Viruses:',
        '',
        'If System is Infected:',
        '',
        '1. Boot in Safe Mode:',
        '• Restart computer',
        '• Press F8 during boot (older Windows)',
        '• Or use Advanced Startup Options',
        '',
        '[UPLOAD: image] Safe Mode',
        '',
        '2. Run Antivirus Scan:',
        '• Use installed antivirus',
        '• Or use portable antivirus scanner',
        '• Run full system scan',
        '',
        '[UPLOAD: image] Virus Scan',
        '',
        '3. Use Removal Tools:',
        '• Many antivirus vendors offer removal tools',
        '• Specific tools for specific threats',
        '• Download from trusted sources',
        '',
        '[UPLOAD: image] Removal Tools',
        '',
        '4. System Restore:',
        '• If available, restore to earlier point',
        '• Before infection occurred',
        '',
        '[UPLOAD: image] System Restore',
        '',
        '5. Last Resort - Reinstall OS:',
        '• Backup important data first',
        '• Format and reinstall operating system',
        '• Restore from clean backup',
        '',
        '[UPLOAD: image] OS Reinstall',
        '',
        'Prevention Tips:',
        '',
        '• Don\'t open suspicious emails',
        '• Don\'t download from untrusted sites',
        '• Keep software updated',
        '• Use strong passwords',
        '• Be cautious with USB drives',
        '• Don\'t disable antivirus',
        '• Use ad blockers',
        '• Be careful with peer-to-peer file sharing',
        '',
        '[UPLOAD: pdf] Complete Virus Protection Guide',
        '',
        '[UPLOAD: video] Antivirus Installation and Configuration',
      ],
    },
  ],
};
export default chapter4Data;
