// screens/dashboard/CHAPTER/chapter1Data.js
const chapter1Image = require('../../../assets/chapter_covers/chapter 1.jpg');
export const chapter1Data = {
  number: 1,
  title: 'ASSEMBLE COMPUTER HARDWARE',
  description: 'Learn the fundamentals of computer hardware components and safe assembly procedures.',
  image: chapter1Image,
  sections: [
    {
      title: 'Computer Basics',
      content: [
        'Computers are electronic devices that process data by executing instructions called programs. A typical computer consists of hardware components such as the CPU, memory, storage devices, and input/output peripherals.',
        '',
        '[UPLOAD: image] Computer System Overview',
        '',
        'Types/Parts of Computers:',
        '',
        'Input Devices:',
        'Input devices allow users to enter data and commands into the computer system. Common input devices include:',
        '• Keyboard - Used for typing text and commands',
        '• Mouse - Pointing device for navigating graphical interfaces',
        '• Scanner - Converts physical documents into digital format',
        '• Microphone - Captures audio input',
        '• Webcam - Captures video input',
        '',
        '[UPLOAD: image] Common Input Devices',
        '',
        'Processing Devices:',
        'The Central Processing Unit (CPU) is the brain of the computer that executes instructions and processes data. The CPU performs arithmetic, logical, control, and input/output operations.',
        '',
        'Key CPU Components:',
        '• Control Unit - Directs operations of the processor',
        '• Arithmetic Logic Unit (ALU) - Performs calculations and logical operations',
        '• Registers - Small, fast storage locations within the CPU',
        '• Cache Memory - High-speed memory for frequently accessed data',
        '',
        '[UPLOAD: image] CPU Architecture Diagram',
        '',
        'Output Devices:',
        'Output devices display or present information processed by the computer:',
        '• Monitor/Display - Visual output device',
        '• Printer - Produces hard copies of documents',
        '• Speakers - Audio output device',
        '• Projector - Displays images on large surfaces',
        '',
        '[UPLOAD: image] Common Output Devices',
        '',
        'Storage Devices:',
        'Storage devices retain data permanently or semi-permanently:',
        '• Hard Disk Drive (HDD) - Traditional magnetic storage',
        '• Solid State Drive (SSD) - Faster flash-based storage',
        '• Optical Drives - CD/DVD/Blu-ray readers and writers',
        '• USB Flash Drives - Portable storage devices',
        '',
        '[UPLOAD: image] Storage Device Comparison',
      ],
    },
    {
      title: 'Occupational Health and Safety',
      content: [
        'Safety is vital when assembling computer hardware. Electrical shocks, electrostatic discharge (ESD), and physical injuries are risks to be aware of.',
        '',
        '[UPLOAD: image] Safety Equipment Setup',
        '',
        'Work Place Safety:',
        '• Ensure adequate lighting in the work area',
        '• Maintain a clean and organized workspace',
        '• Keep work area free from clutter and obstacles',
        '• Use proper ventilation to avoid inhaling dust',
        '• Have a fire extinguisher nearby',
        '• Keep emergency contact numbers accessible',
        '',
        '[UPLOAD: image] Proper Workspace Setup',
        '',
        'Computer System Safety:',
        '• Always turn off and unplug the computer before working on it',
        '• Wait for capacitors to discharge (30 seconds minimum)',
        '• Never work on a computer while it is plugged in',
        '• Use anti-static mats on work surfaces',
        '• Keep liquids away from electronic components',
        '• Handle components by edges, avoid touching circuitry',
        '',
        '[UPLOAD: video] Safe Computer Handling Procedures',
        '',
        'Technician Safety:',
        '• Wear an anti-static wrist strap connected to ground',
        '• Remove jewelry and watches that could cause short circuits',
        '• Use proper lifting techniques for heavy components',
        '• Take regular breaks to avoid fatigue',
        '• Keep first aid kit accessible',
        '• Report any injuries immediately',
        '',
        'Warning:',
        'Never work on live electrical equipment. Always disconnect power before servicing.',
        '',
        '[UPLOAD: pdf] Complete OHS Guidelines Document',
      ],
    },
    {
      title: 'Use of Hand Tools',
      content: [
        'Proper use of hand tools such as screwdrivers, pliers, and anti-static wrist straps is essential for safe and efficient computer assembly.',
        '',
        '[UPLOAD: image] Essential Computer Repair Tools',
        '',
        'Hand Tools:',
        '',
        'Phillips Head Screwdriver:',
        'The most common screwdriver for computer assembly. Used for case screws, motherboard mounting screws, and component installation. Available in various sizes (PH0, PH1, PH2).',
        '',
        '[UPLOAD: image] Phillips Screwdriver Types',
        '',
        'Flat Head Screwdriver:',
        'Used for specific screws and as a careful prying tool. Less common in modern computers but still useful for certain applications.',
        '',
        'Torx Screwdriver:',
        'Star-shaped driver used for specialized screws in some computer cases and components. Common sizes include T5, T6, T8, T10.',
        '',
        'Anti-static Wrist Strap:',
        'Essential safety equipment to prevent electrostatic discharge (ESD) that can damage sensitive components. Must be properly grounded.',
        '',
        '[UPLOAD: image] Proper Anti-static Strap Usage',
        '',
        'Cleaning Tools:',
        '',
        'Compressed Air:',
        'Used to remove dust from components, fans, and heat sinks. Never tilt the can while spraying.',
        '',
        'Isopropyl Alcohol:',
        'Used with lint-free cloths to clean thermal paste and other residues. Use 90% or higher concentration.',
        '',
        'Lint-free Cloths:',
        'Microfiber or specialized cloths for cleaning components without leaving residue.',
        '',
        '[UPLOAD: image] Cleaning Tools and Materials',
        '',
        'Diagnostic Tools:',
        '',
        'Multimeter:',
        'Measures voltage, current, and resistance. Essential for testing power supplies and circuits.',
        '',
        'POST Card:',
        'Power-On Self-Test card that displays error codes during system startup for troubleshooting.',
        '',
        'Cable Testers:',
        'Used to verify network cables and other connections are properly wired.',
        '',
        '[UPLOAD: video] Tool Usage Demonstration',
      ],
    },
    {
      title: 'Motherboard Parts Identification',
      content: [
        'The motherboard is the main circuit board connecting all components. Understanding its parts is necessary for assembly and troubleshooting.',
        '',
        '[UPLOAD: image] Motherboard Overview Diagram',
        '',
        'Key Motherboard Parts:',
        '',
        'CPU Socket:',
        'Where the processor is installed. Different sockets support different CPU types (LGA, PGA, BGA). Common sockets include LGA 1151, AM4, LGA 1700.',
        '',
        '[UPLOAD: image] CPU Socket Types',
        '',
        'RAM Slots:',
        'Memory modules installation points. Typically 2-4 slots, supporting DDR3, DDR4, or DDR5 depending on motherboard generation.',
        '',
        'Power Connectors:',
        '• 24-pin ATX main power connector - Primary system power',
        '• 8-pin (or 4+4) CPU power connector - Processor power supply',
        '• Additional PCIe power for high-end motherboards',
        '',
        '[UPLOAD: image] Power Connector Locations',
        '',
        'Peripheral Slots:',
        '• PCI (Peripheral Component Interconnect) - Legacy expansion slots',
        '• PCIe x1 - Small expansion cards (sound cards, network cards)',
        '• PCIe x16 - Graphics cards and high-speed expansion',
        '• M.2 Slots - Modern SSD and Wi-Fi card installation',
        '',
        '[UPLOAD: image] Expansion Slot Types',
        '',
        'Chipset:',
        'Controls data flow between CPU, memory, and peripherals. Located near the CPU socket, often covered by a heat sink.',
        '',
        'BIOS/UEFI Chip:',
        'Stores firmware that initializes hardware during boot. May be removable or soldered.',
        '',
        'CMOS Battery:',
        'Maintains system settings, date, and time when powered off. Typically a CR2032 coin cell battery.',
        '',
        '[UPLOAD: image] Chipset and BIOS Components',
        '',
        'Motherboard Connections:',
        '',
        'Front Panel Connectors:',
        '• Power switch (PWR_SW)',
        '• Reset switch (RESET)',
        '• Power LED (PWR_LED)',
        '• HDD LED',
        '• USB headers',
        '• Audio headers',
        '',
        '[UPLOAD: image] Front Panel Connector Diagram',
        '',
        'Common Motherboard Ports:',
        '• USB Ports (2.0, 3.0, 3.1, Type-C) - Universal Serial Bus connections',
        '• HDMI, VGA, DVI, DisplayPort - Display output connections',
        '• Ethernet Port (RJ-45) - Network connectivity',
        '• Audio Jacks - Sound input and output (3.5mm)',
        '• PS/2 Ports - Legacy keyboard and mouse (if present)',
        '',
        '[UPLOAD: image] Rear I/O Port Layout',
        '',
        '[UPLOAD: video] Motherboard Component Tour',
      ],
    },
    {
      title: 'Identifying RAMs',
      content: [
        "Random Access Memory (RAM) is the computer's short-term memory vital for running programs and storing active data.",
        '',
        '[UPLOAD: image] RAM Module Overview',
        '',
        'Types of RAM:',
        '',
        'DIMM (Dual In-line Memory Module):',
        'Standard RAM for desktop computers. Physical characteristics vary by generation:',
        '• DDR3: 240 pins, operates at 1.5V',
        '• DDR4: 288 pins, operates at 1.2V, notch position different from DDR3',
        '• DDR5: 288 pins, operates at 1.1V, improved performance',
        '',
        '[UPLOAD: image] DIMM Module Comparison',
        '',
        'SO-DIMM (Small Outline DIMM):',
        'Compact RAM designed for laptops and small form factor systems:',
        '• DDR3 SO-DIMM: 204 pins',
        '• DDR4 SO-DIMM: 260 pins',
        '• DDR5 SO-DIMM: 262 pins',
        '',
        '[UPLOAD: image] SO-DIMM vs DIMM Size Comparison',
        '',
        'Key Features to Consider:',
        '',
        'Capacity:',
        'Common sizes: 4GB, 8GB, 16GB, 32GB per module. Total system RAM depends on number of modules and motherboard support.',
        '',
        'Speed (Frequency):',
        'Measured in MHz (e.g., 2400MHz, 3200MHz, 3600MHz). Higher speeds provide better performance but must be supported by motherboard and CPU.',
        '',
        'Timing (CAS Latency):',
        'Lower CAS latency (e.g., CL16 vs CL18) indicates faster response time. Format: CL-tRCD-tRP-tRAS (e.g., 16-18-18-36).',
        '',
        '[UPLOAD: image] RAM Speed and Timing Labels',
        '',
        'Voltage:',
        'Different DDR generations operate at different voltages. Using incorrect voltage can damage components.',
        '',
        'Single vs Dual Channel:',
        'Installing RAM in pairs (dual channel) can improve performance. Check motherboard manual for optimal slot configuration.',
        '',
        '[UPLOAD: image] Dual Channel Configuration',
        '',
        'Compatibility Considerations:',
        '• Check motherboard specifications for supported RAM types',
        '• Verify maximum capacity per slot and total system capacity',
        '• Ensure CPU supports the RAM speed',
        '• Mixing different speeds will run all modules at the slowest speed',
        '',
        '[UPLOAD: pdf] RAM Compatibility Guide',
        '',
        '[UPLOAD: video] RAM Installation Tutorial',
      ],
    },
    {
      title: 'Power Supply Unit',
      content: [
        'The power supply unit (PSU) converts AC power from the wall outlet to DC power needed by computer components.',
        '',
        '[UPLOAD: image] Power Supply Unit Overview',
        '',
        'Important Concepts:',
        '',
        'Wattage Rating:',
        'Total power capacity measured in watts (W). Common ratings: 450W, 550W, 650W, 750W, 850W, 1000W+. Choose based on component power requirements with 20-30% headroom.',
        '',
        '[UPLOAD: image] PSU Wattage Calculator',
        '',
        'Efficiency Ratings:',
        '80 Plus certifications indicate energy efficiency:',
        '• 80 Plus (80% efficiency at 20%, 50%, 100% load)',
        '• 80 Plus Bronze (82-85%)',
        '• 80 Plus Silver (85-88%)',
        '• 80 Plus Gold (87-90%)',
        '• 80 Plus Platinum (90-92%)',
        '• 80 Plus Titanium (90-94%)',
        '',
        '[UPLOAD: image] 80 Plus Efficiency Chart',
        '',
        'Modular vs Non-modular:',
        '• Non-modular: All cables permanently attached',
        '• Semi-modular: Essential cables attached, others detachable',
        '• Fully modular: All cables detachable for better cable management',
        '',
        '[UPLOAD: image] Modular PSU Types',
        '',
        'Power Connectors:',
        '',
        '24-pin ATX Motherboard Connector:',
        'Main system power. Provides +3.3V, +5V, +12V, and ground lines. Can be 20+4 pin for backward compatibility.',
        '',
        '8-pin (4+4) CPU Connector:',
        'Processor power supply. Provides +12V to CPU. Can split into two 4-pin connectors for older motherboards.',
        '',
        'PCIe Connectors:',
        'Graphics card power. Available as 6-pin, 8-pin (6+2), or combinations. High-end GPUs may require multiple connectors.',
        '',
        'SATA Connectors:',
        'Power for SATA storage devices (HDDs, SSDs, optical drives). Provides +3.3V, +5V, +12V.',
        '',
        'Molex Connectors:',
        'Legacy 4-pin power connector for older devices. Provides +5V and +12V.',
        '',
        '[UPLOAD: image] PSU Connector Types',
        '',
        'Power Supply Color Codes:',
        'Understanding wire colors helps with troubleshooting:',
        '• Yellow: +12V',
        '• Red: +5V',
        '• Orange: +3.3V',
        '• Black: Ground (0V)',
        '• Purple: +5V SB (standby voltage)',
        '• Green: /PS_ON (power on signal)',
        '• Grey: PWR_OK (power good signal)',
        '• White: -5V (optional, legacy)',
        '• Blue: -12V',
        '',
        '[UPLOAD: image] PSU Wire Color Code Chart',
        '',
        'Safety Considerations:',
        '• Never open a PSU - capacitors can hold dangerous charge',
        '• Use PSU tester or multimeter to verify voltages',
        '• Ensure adequate ventilation for PSU cooling',
        '• Match PSU form factor to case (ATX, SFX, TFX)',
        '',
        '[UPLOAD: video] PSU Installation and Testing',
        '',
        '[UPLOAD: pdf] PSU Selection Guide',
      ],
    },
    {
      title: 'Steps to a Safe and Successful Disassembly and Assembly',
      content: [
        'Follow these systematic steps for safe and successful computer disassembly and reassembly.',
        '',
        '[UPLOAD: image] Complete Computer System',
        '',
        'Disassembly Process:',
        '',
        '1. Preparation:',
        'Gather all necessary tools (screwdrivers, anti-static strap, containers for screws). Ensure adequate lighting and workspace.',
        '',
        '2. Power Down and Disconnect:',
        'Shut down the computer properly, then disconnect all cables (power, monitor, keyboard, mouse, USB devices, network cable).',
        '',
        '3. Ground Yourself:',
        'Put on anti-static wrist strap and connect to grounded surface or unpainted metal part of case.',
        '',
        '[UPLOAD: image] Anti-static Setup',
        '',
        '4. Remove Case Cover:',
        'Locate and remove case screws (usually at rear). Slide or lift off side panel carefully. Some cases have tool-less mechanisms.',
        '',
        '5. Document Connections:',
        'Take photos or notes of cable connections before disconnecting. Label cables if necessary.',
        '',
        '[UPLOAD: image] Documenting Connections',
        '',
        '6. Disconnect Internal Cables:',
        'Carefully disconnect power cables, data cables (SATA, IDE), and front panel connectors. Note their positions.',
        '',
        '7. Remove Expansion Cards:',
        'Remove any expansion cards (GPU, sound card, network card) by releasing retention clips and unscrewing mounting brackets.',
        '',
        '8. Remove Storage Devices:',
        'Disconnect and remove hard drives and SSDs. Note mounting positions and orientation.',
        '',
        '9. Remove RAM Modules:',
        'Release retention clips on both ends of RAM slots and carefully remove modules. Handle by edges only.',
        '',
        '[UPLOAD: image] RAM Removal Process',
        '',
        '10. Remove CPU Cooler:',
        'Disconnect fan power, remove mounting screws or clips, and carefully lift cooler. May require twisting if thermal paste is dried.',
        '',
        '11. Remove CPU:',
        'Lift retention arm, carefully remove CPU. Handle by edges, avoid touching pins or contacts.',
        '',
        '12. Remove Motherboard:',
        'Remove all mounting screws, disconnect any remaining cables, and carefully lift motherboard out of case.',
        '',
        '13. Remove Power Supply:',
        'Disconnect all PSU cables, remove mounting screws, and slide PSU out of case.',
        '',
        '[UPLOAD: video] Complete Disassembly Process',
        '',
        'Assembly Process:',
        '',
        'Assembly follows the reverse order of disassembly:',
        '',
        '1. Install Power Supply:',
        'Position PSU in case, secure with screws, route cables appropriately.',
        '',
        '2. Install Motherboard:',
        'Place motherboard on standoffs, ensure proper alignment, secure with screws. Do not overtighten.',
        '',
        '[UPLOAD: image] Motherboard Installation',
        '',
        '3. Install CPU:',
        'Lift retention arm, align CPU correctly (match triangle/notch), lower retention arm to lock CPU in place.',
        '',
        '4. Apply Thermal Paste:',
        'Apply small amount (pea-sized) of thermal paste to CPU center if not pre-applied on cooler.',
        '',
        '[UPLOAD: image] Thermal Paste Application',
        '',
        '5. Install CPU Cooler:',
        'Position cooler, secure with mounting mechanism, connect fan power to CPU_FAN header.',
        '',
        '6. Install RAM:',
        'Align notch, press firmly until retention clips snap into place. Install in recommended slots for dual channel if applicable.',
        '',
        '[UPLOAD: image] RAM Installation',
        '',
        '7. Install Storage Devices:',
        'Mount drives in drive bays, connect SATA data and power cables.',
        '',
        '8. Install Expansion Cards:',
        'Remove slot covers, insert cards firmly, secure with screws, connect any required power cables.',
        '',
        '9. Connect Internal Cables:',
        'Connect all power cables (24-pin ATX, 8-pin CPU, PCIe, SATA power). Connect data cables (SATA). Connect front panel connectors according to motherboard manual.',
        '',
        '[UPLOAD: image] Cable Management',
        '',
        '10. Connect Front Panel:',
        'Refer to motherboard manual for front panel connector pinout. Connect power switch, reset switch, LEDs, USB headers, audio headers.',
        '',
        '[UPLOAD: image] Front Panel Connections',
        '',
        '11. Final Checks:',
        'Verify all connections are secure, no loose screws in case, all cables properly routed, no tools left inside.',
        '',
        '12. Install Case Cover:',
        'Replace side panel, secure with screws.',
        '',
        '13. Connect External Cables:',
        'Connect power cable, monitor, keyboard, mouse, and other peripherals.',
        '',
        '14. Power On and Test:',
        'Press power button, verify POST (Power-On Self-Test), check BIOS/UEFI recognizes all components, proceed with OS installation if needed.',
        '',
        '[UPLOAD: video] Complete Assembly Process',
        '',
        'Important Reminders:',
        '• Take your time - rushing leads to mistakes',
        '• Stay organized - use containers for screws',
        '• Handle components by edges only',
        '• Never force components into place',
        '• Double-check all connections before powering on',
        '• Keep workspace clean and well-lit',
        '• Refer to component manuals when unsure',
        '',
        '[UPLOAD: pdf] Complete Assembly Guide',
      ],
    },
  ],
};
export default chapter1Data;