// screens/dashboard/CHAPTER/chapter2Data.js
const chapter2Image = require('../../../assets/chapter_covers/chapter 2.jpg');
export const chapter2Data = {
   number: 2,
  title: 'INSTALL OPERATING SYSTEM AND DRIVERS',
  description: 'Learn to prepare installation media and configure system settings.',
  image: chapter2Image,
  sections: [
    {
      title: 'Windows Server 2008 R2 Overview',
      content: [
        'Windows Server 2008 R2 is a server operating system designed for enterprise environments. This module focuses on installing Windows Server 2008 R2 Standard x64 bit edition.',
        '',
        '[UPLOAD: image] Windows Server 2008 R2 Interface',
        '',
        'Key Features:',
        '• 64-bit architecture for improved performance',
        '• Enhanced security features',
        '• Server management tools',
        '• Active Directory support',
        '• Network services and roles',
        '',
        'System Requirements:',
        '• Processor: 1.4 GHz x64 processor',
        '• RAM: 512 MB minimum (2 GB recommended)',
        '• Hard Disk: 32 GB minimum free space',
        '• Network adapter',
        '• DVD drive or USB boot capability',
        '',
        '[UPLOAD: pdf] Windows Server 2008 R2 System Requirements',
      ],
    },
    {
      title: 'Making ISO Image Using PowerISO',
      content: [
        'PowerISO is a powerful CD/DVD/BD image file processing tool that can create, extract, burn, and edit ISO files.',
        '',
        '[UPLOAD: image] PowerISO Interface',
        '',
        'Downloading PowerISO:',
        '1. Visit the official PowerISO website',
        '2. Download the latest version compatible with your system',
        '3. Save the installer to a known location',
        '',
        '[UPLOAD: image] PowerISO Download Page',
        '',
        'Installing PowerISO:',
        '1. Run the downloaded installer',
        '2. Follow the installation wizard',
        '3. Accept the license agreement',
        '4. Choose installation directory',
        '5. Complete the installation',
        '',
        '[UPLOAD: image] PowerISO Installation Steps',
        '',
        'Creating ISO Image:',
        '',
        'From CD/DVD:',
        '1. Launch PowerISO',
        '2. Insert the source CD/DVD into the drive',
        '3. Click "Tools" menu, then "Make CD/DVD Image"',
        '4. Select the source drive',
        '5. Choose output file name and location',
        '6. Select image format (ISO, BIN, etc.)',
        '7. Click "OK" to start creating the image',
        '',
        '[UPLOAD: image] Creating ISO from Disc',
        '',
        'From Files and Folders:',
        '1. Launch PowerISO',
        '2. Click "New" to create a new image project',
        '3. Add files and folders by dragging or using "Add" button',
        '4. Click "Save" button',
        '5. Choose ISO as output format',
        '6. Enter file name and location',
        '7. Click "Save" to create the ISO file',
        '',
        '[UPLOAD: image] Creating ISO from Files',
        '',
        'Important Notes:',
        '• Ensure you have sufficient disk space for the ISO file',
        '• ISO files can be large (several GB for OS images)',
        '• Verify the ISO file integrity after creation',
        '• Store ISO files in a safe location',
        '',
        '[UPLOAD: video] Complete PowerISO Tutorial',
      ],
    },
    {
      title: 'Creating Bootable Flash Drive using Rufus',
      content: [
        'Rufus is a utility that helps format and create bootable USB flash drives, such as USB keys/pendrives, memory sticks, etc. It is particularly useful for creating bootable USB drives from ISO images.',
        '',
        '[UPLOAD: image] Rufus Interface',
        '',
        'Downloading Rufus:',
        '1. Visit the official Rufus website (rufus.ie)',
        '2. Download the portable version (recommended) or installer',
        '3. No installation required for portable version',
        '',
        '[UPLOAD: image] Rufus Download',
        '',
        'Requirements:',
        '• USB flash drive (4GB or higher recommended)',
        '• ISO image file of the operating system',
        '• Backup important data from USB drive (will be erased)',
        '',
        'Creating Bootable Flash Drive:',
        '',
        '1. Insert USB Flash Drive:',
        'Connect your USB drive to the computer. Ensure it has at least 4GB capacity for Windows Server 2008 R2.',
        '',
        '[UPLOAD: image] USB Drive Connection',
        '',
        '2. Launch Rufus:',
        'Run Rufus.exe (if portable) or launch from Start Menu (if installed).',
        '',
        '3. Select USB Device:',
        'In the "Device" dropdown, select your USB flash drive. Be careful to select the correct drive as all data will be erased.',
        '',
        '[UPLOAD: image] Device Selection',
        '',
        '4. Select Boot Selection:',
        'Click "SELECT" button and browse to your ISO image file. Select the Windows Server 2008 R2 ISO file.',
        '',
        '5. Choose Partition Scheme:',
        '• GPT: For UEFI systems (modern computers)',
        '• MBR: For BIOS/Legacy systems (older computers)',
        'Match this with your target system\'s firmware type.',
        '',
        '[UPLOAD: image] Partition Scheme Options',
        '',
        '6. Select Target System:',
        '• UEFI (non CSM): For modern UEFI systems',
        '• BIOS (or UEFI-CSM): For legacy BIOS systems',
        '',
        '7. File System:',
        'Usually set to NTFS for Windows installations. Rufus will set this automatically.',
        '',
        '8. Cluster Size:',
        'Leave as default (4096 bytes) unless you have specific requirements.',
        '',
        '9. Volume Label:',
        'Optional: Enter a name for your USB drive (e.g., "WIN_SERVER_2008R2").',
        '',
        '[UPLOAD: image] Rufus Configuration Settings',
        '',
        '10. Start the Process:',
        'Click "START" button. You will receive a warning that all data on the USB drive will be destroyed. Click "OK" to proceed.',
        '',
        '[UPLOAD: image] Rufus Warning Dialog',
        '',
        '11. Wait for Completion:',
        'The process may take 10-30 minutes depending on USB speed and ISO file size. Do not remove the USB drive during this process.',
        '',
        '[UPLOAD: image] Rufus Progress',
        '',
        '12. Verification:',
        'Once complete, Rufus will show "READY" status. You can safely close Rufus and eject the USB drive.',
        '',
        'Important Tips:',
        '• Always backup data from USB drive before creating bootable media',
        '• Use a reliable USB drive (avoid cheap, unknown brands)',
        '• Ensure USB drive is not write-protected',
        '• Close any programs that might be accessing the USB drive',
        '• If process fails, try a different USB port or USB drive',
        '',
        '[UPLOAD: video] Complete Rufus Bootable USB Creation',
        '',
        '[UPLOAD: pdf] Rufus User Guide',
      ],
    },
    {
      title: 'Installing Windows Server 2008 R2 Standard x64 bit',
      content: [
        'This section covers the complete installation process for Windows Server 2008 R2 Standard x64 bit edition.',
        '',
        '[UPLOAD: image] Windows Server 2008 R2 Installation',
        '',
        'Pre-Installation Checklist:',
        '• Bootable USB drive with Windows Server 2008 R2',
        '• Valid product key (if required)',
        '• Backup of important data',
        '• Network cable (if network installation needed)',
        '• Driver files for hardware (if needed)',
        '',
        '[UPLOAD: pdf] Pre-Installation Checklist',
        '',
        'Step 1: Change BIOS Boot Order',
        '',
        '1. Power on the computer and immediately press the BIOS key (commonly Del, F2, F10, F12, or Esc)',
        '',
        '[UPLOAD: image] BIOS Entry Screen',
        '',
        '2. Navigate to "Boot" or "Boot Order" section',
        '',
        '3. Set USB device as first boot option',
        '',
        '[UPLOAD: image] BIOS Boot Order Settings',
        '',
        '4. Save changes and exit (usually F10)',
        '',
        '5. Computer will restart and boot from USB drive',
        '',
        '[UPLOAD: image] Booting from USB',
        '',
        'Step 2: Windows Setup Initialization',
        '',
        '1. Wait for "Windows is loading files" screen',
        '',
        '2. Select language, time and currency format, and keyboard input method',
        '',
        '[UPLOAD: image] Language Selection',
        '',
        '3. Click "Next"',
        '',
        '4. Click "Install Now" on the next screen',
        '',
        '[UPLOAD: image] Install Now Screen',
        '',
        'Step 3: Product Key and License',
        '',
        '1. Enter product key if prompted (or skip for evaluation)',
        '',
        '[UPLOAD: image] Product Key Entry',
        '',
        '2. Select Windows Server 2008 R2 Standard (Server Core Installation) or (Full Installation)',
        '',
        'Note: Full Installation includes GUI, Server Core is command-line only',
        '',
        '3. Accept the license terms',
        '',
        '4. Click "Next"',
        '',
        '[UPLOAD: image] Edition Selection',
        '',
        'Step 4: Installation Type',
        '',
        '1. Select "Custom (advanced)" for clean installation',
        '',
        '[UPLOAD: image] Installation Type Selection',
        '',
        'Step 5: Disk Partitioning',
        '',
        '1. Select the hard drive where you want to install Windows',
        '',
        '2. Click "Drive options (advanced)"',
        '',
        '3. Delete existing partitions if needed (this will erase all data)',
        '',
        '[UPLOAD: image] Disk Management Screen',
        '',
        '4. Create partitions as specified:',
        '• Drive C: 40% of total disk space',
        '• Drive D: 60% of total disk space',
        '',
        'To create partitions:',
        'a. Select unallocated space',
        'b. Click "New"',
        'c. Enter size for C: drive (40% of total)',
        'd. Click "Apply"',
        'e. Repeat for D: drive with remaining space',
        '',
        '[UPLOAD: image] Creating Partitions',
        '',
        '5. Select the partition for C: drive (usually the first partition)',
        '',
        '6. Click "Next" to begin installation',
        '',
        '[UPLOAD: image] Partition Layout',
        '',
        'Step 6: Installation Process',
        '',
        'Windows will now:',
        '1. Copy Windows files',
        '2. Expand Windows files',
        '3. Install features',
        '4. Install updates',
        '5. Complete installation',
        '',
        'This process takes approximately 20-40 minutes. The computer will restart several times.',
        '',
        '[UPLOAD: image] Installation Progress',
        '',
        'Important: Do not remove the USB drive or power off during installation.',
        '',
        '[UPLOAD: video] Installation Process',
        '',
        'Step 7: Set Administrator Password',
        '',
        'After installation completes and system restarts:',
        '',
        '1. You will be prompted to set a password for the Administrator account',
        '',
        '2. Enter password: asian@12345 (as per module requirements)',
        '',
        '3. Confirm the password',
        '',
        '[UPLOAD: image] Password Setup',
        '',
        '4. Click the arrow or press Enter',
        '',
        'Password Requirements:',
        '• Minimum 7 characters (Windows Server 2008 R2)',
        '• Should include uppercase, lowercase, numbers, and special characters for security',
        '• Keep password secure and documented',
        '',
        '[UPLOAD: image] Password Requirements',
        '',
        'Step 8: Initial Configuration',
        '',
        '1. Log in with Administrator account',
        '',
        '2. Initial Configuration Tasks (ICT) window will appear',
        '',
        '[UPLOAD: image] Initial Configuration Tasks',
        '',
        '3. Configure the following:',
        '• Set time zone',
        '• Configure networking',
        '• Enable Remote Desktop (if needed)',
        '• Download and install updates',
        '• Add roles and features',
        '',
        '[UPLOAD: image] ICT Configuration Options',
        '',
        'Step 9: Windows Update',
        '',
        '1. Connect to the internet',
        '',
        '2. Open Windows Update from Control Panel or Server Manager',
        '',
        '3. Check for updates',
        '',
        '4. Install all important updates',
        '',
        '5. Restart if required',
        '',
        '[UPLOAD: image] Windows Update',
        '',
        'Step 10: Verification',
        '',
        'Verify successful installation:',
        '',
        '1. Check System Properties to confirm OS version',
        '',
        '[UPLOAD: image] System Properties',
        '',
        '2. Verify disk partitions (C: and D:)',
        '',
        '[UPLOAD: image] Disk Management',
        '',
        '3. Test network connectivity',
        '',
        '4. Verify all hardware is recognized in Device Manager',
        '',
        '[UPLOAD: image] Device Manager',
        '',
        'Common Installation Issues:',
        '',
        'Issue: Installation fails or hangs',
        'Solution: Check hardware compatibility, ensure adequate RAM and disk space, verify ISO file integrity',
        '',
        'Issue: Cannot find hard drive',
        'Solution: Load storage drivers during installation, check SATA mode in BIOS (AHCI/IDE)',
        '',
        'Issue: Blue screen during installation',
        'Solution: Check hardware compatibility, test RAM with memtest, verify ISO file',
        '',
        '[UPLOAD: pdf] Troubleshooting Installation Issues',
        '',
        '[UPLOAD: video] Complete Installation Walkthrough',
      ],
    },
    {
      title: 'Driver Installation for Peripherals and Devices',
      content: [
        'After installing the operating system, you need to install drivers for all hardware components to ensure proper functionality.',
        '',
        '[UPLOAD: image] Device Manager with Missing Drivers',
        '',
        'Understanding Drivers:',
        'Drivers are software programs that allow the operating system to communicate with hardware devices. Without proper drivers, devices may not work or work with limited functionality.',
        '',
        'Checking for Missing Drivers:',
        '',
        '1. Open Device Manager:',
        '• Right-click "Computer" → "Manage" → "Device Manager"',
        '• Or press Windows + X → Device Manager',
        '',
        '[UPLOAD: image] Accessing Device Manager',
        '',
        '2. Look for devices with yellow exclamation marks (!)',
        '',
        '3. These indicate devices without proper drivers',
        '',
        '[UPLOAD: image] Devices Needing Drivers',
        '',
        'Priority Drivers to Install:',
        '',
        '1. Chipset Drivers:',
        'Essential for motherboard communication. Install from motherboard manufacturer\'s website.',
        '',
        '[UPLOAD: image] Chipset Driver Installation',
        '',
        '2. Network Adapter Drivers:',
        'Required for internet connectivity. Critical for downloading other drivers.',
        '',
        '[UPLOAD: image] Network Driver Installation',
        '',
        '3. Graphics Drivers:',
        'For display functionality. Install from GPU manufacturer (NVIDIA, AMD, Intel).',
        '',
        '[UPLOAD: image] Graphics Driver Installation',
        '',
        '4. Audio Drivers:',
        'For sound functionality. Usually from motherboard manufacturer or Realtek.',
        '',
        '[UPLOAD: image] Audio Driver Installation',
        '',
        '5. Storage Controller Drivers:',
        'For SATA/RAID controllers. May be needed during OS installation.',
        '',
        '6. USB Drivers:',
        'Usually included with chipset drivers.',
        '',
        'Methods of Driver Installation:',
        '',
        'Method 1: Windows Update',
        '1. Connect to internet',
        '2. Open Windows Update',
        '3. Check for updates',
        '4. Install driver updates if available',
        '',
        '[UPLOAD: image] Windows Update Drivers',
        '',
        'Method 2: Manufacturer Websites',
        '1. Identify hardware manufacturer and model',
        '2. Visit manufacturer\'s support website',
        '3. Download appropriate drivers for Windows Server 2008 R2 x64',
        '4. Run installer and follow prompts',
        '',
        '[UPLOAD: image] Manufacturer Driver Download',
        '',
        'Method 3: Driver Installation Discs',
        'Many motherboards and devices come with driver discs:',
        '1. Insert the driver disc',
        '2. Run the setup or autorun program',
        '3. Follow installation wizard',
        '',
        '[UPLOAD: image] Driver Disc Installation',
        '',
        'Method 4: Device Manager Update',
        '1. Open Device Manager',
        '2. Right-click device with issue',
        '3. Select "Update Driver Software"',
        '4. Choose "Browse my computer for driver software"',
        '5. Point to driver folder or disc',
        '',
        '[UPLOAD: image] Manual Driver Update',
        '',
        'Installing Network Device Driver:',
        '',
        'This is often the first driver needed to get internet access:',
        '',
        '1. Identify network adapter:',
        '• Check Device Manager for "Network adapters" or "Unknown device"',
        '• Note the device ID or model number',
        '',
        '[UPLOAD: image] Identifying Network Adapter',
        '',
        '2. Download driver:',
        '• Use another computer with internet access',
        '• Visit motherboard or network adapter manufacturer website',
        '• Download Windows Server 2008 R2 x64 driver',
        '• Transfer to USB drive',
        '',
        '3. Install driver:',
        '• Copy driver files to server',
        '• Run setup.exe or update via Device Manager',
        '• Restart if prompted',
        '',
        '[UPLOAD: image] Network Driver Setup',
        '',
        '4. Verify installation:',
        '• Check Device Manager - no yellow exclamation mark',
        '• Test network connectivity',
        '• Verify IP address assignment',
        '',
        '[UPLOAD: image] Network Connection Verified',
        '',
        'Best Practices:',
        '• Install drivers in order: Chipset → Network → Graphics → Audio → Others',
        '• Restart after major driver installations',
        '• Keep driver installation files for future use',
        '• Create system restore point before major driver updates',
        '• Only install drivers from trusted sources',
        '',
        '[UPLOAD: video] Complete Driver Installation Guide',
        '',
        '[UPLOAD: pdf] Driver Installation Best Practices',
      ],
    },
  ],
};
export default chapter2Data;